### ISSUE TITLE
Update Bakta

### ISSUE THREAD

**Issue by bebatut** [usegalaxy-au/usegalaxy-au-tools#1127]
Hi,

I tried to run the [Bacterial Genome Annotation tutorial](https://training.galaxyproject.org/training-material/topics/genome-annotation/tutorials/bacterial-genome-annotation/tutorial.html) on Galaxy Australia to prepare for the GTA.
Bakta should be updated.

Can Bakta and its DM be updated? I was not sure how to request it with a PR.

Thanks for your help,

Bérénice

**Comment by cat-bro** [comment]
Hi Bérénice, no need to make a PR for this, we will update it.

**Comment by cat-bro** [comment]
Thank you for raising this. bakta has been updated now.

**Comment by bebatut** [comment]
Thanks a lot!
