### ISSUE TITLE
New software request: pipe_t  31:e4281dad3291

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#201]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: pipe_t  31:e4281dad3291
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/view/davidecangelosi/pipe_t/e4281dad3291

**Comment by cat-bro** [comment]
Installed in #207 #208
