### ISSUE TITLE
New software request: Maker

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#202]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Maker
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> no

<label for="softURL">URL for software code</label>: http://www.yandell-lab.org/software/maker.html

**Comment by Slugger70** [comment]
There seem to be issues getting this tool to run. We are having problems with openmpi exec in slurm for some reason. Works fine for the local job runner but not with the slurm runner. The error is related to openmpi not recognising the node format for slurm. Could be a version conflict.

**Comment by cat-bro** [comment]
new version installed and working
