### ISSUE TITLE
New software request: msi_filtering

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#235]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: msi_filtering
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/view/galaxyp/cardinal_filtering/a8157342d9a3

**Comment by cat-bro** [comment]
installed https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/239
