### ISSUE TITLE
New software request: Sniffles (current)

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#267]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Sniffles (current)
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> no

<label for="softURL">URL for software code</label>: https://github.com/fritzsedlazeck/Sniffles

**Comment by cat-bro** [comment]
Resolved! https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/297 https://github.com/galaxyproject/tools-iuc/pull/3187
