### ISSUE TITLE
New software request: Nucmer

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#475]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Nucmer
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/view/iuc/mummer_nucmer/636b049e6141

**Comment by cat-bro** [comment]
We could not install some of the mummer tools because libGL.so.1 could not be found, still a WIP
https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/442
