### ISSUE TITLE
New software request: Picrust latest version

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#53]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Picrust latest version
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>:  https://toolshed.g2.bx.psu.edu/view/iuc/suite_picrust/815f6f49df0e

**Comment by cat-bro** [comment]
resolved here https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/54
