### ISSUE TITLE
Tool blacklist

### ISSUE THREAD

**Issue by Slugger70** [usegalaxy-au/usegalaxy-au-tools#58]
We may have occasions where a trusted owner has a less than trusted tool. (e.g. GATK) 

Therefore, we will need a tool blacklist. This will also help with tools that continually fail tests as well. (e.g. Abricate)

**Comment by cat-bro** [comment]
Something like this:
trusted_owners.yml

```
trusted_owners:
- owner: iuc
  exceptions:
  - abricate
  - gatk2
- owner: simon-gladman
- owner: nml
- owner: bgruening
- owner: devteam
```

Can confirm after the update script has finished.

**Comment by Slugger70** [comment]
yeah looks good
