### ISSUE TITLE
New software request: Parse Parameter Value

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#595]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Parse Parameter Value
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> no

<label for="softURL">URL for software code</label>:

**Comment by cat-bro** [comment]
This is a galaxy builtin that only shows up from the workflow editor.
