### ISSUE TITLE
New software request: cellxgene

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#596]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: cellxgene
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> no

<label for="softURL">URL for software code</label>: It's available on Human Cell Atlas Galaxy under interactive_tool_cellxgene. GitHub: https://github.com/chanzuckerberg/cellxgene

**Comment by nghiaagent** [comment]
Interestingly, it's available in HCA but not on the Tool Shed.

https://humancellatlas.usegalaxy.eu/root?tool_id=interactive_tool_cellxgene
