### ISSUE TITLE
New software request: LINKS v2.0.1

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#712]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: LINKS v2.0.1
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/view/iuc/links/7acd9ade2dd1

**Comment by cat-bro** [comment]
Installed
https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/713
