### ISSUE TITLE
New software request: Unicycler

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#714]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: Unicycler
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/view/iuc/unicycler/9e3e80cc4ad4

**Comment by cat-bro** [comment]
Unicycler is already installed and updated regularly.  IM has replied to the request.
