### ISSUE TITLE
New software request: SMAGEXP

### ISSUE THREAD

**Issue by QFAB-Ops** [usegalaxy-au/usegalaxy-au-tools#89]
# New software requested submitted - Galaxy Australia

<label for="typeInstall">What type of resource would you like installed?</label> tool

<label for="toolName">Name and version of software/tool to be installed/updated</label>: SMAGEXP
<label for="toolAvail">Is the tool available from the Galaxy Toolshed?</label> yes

<label for="toolURL">URL to the tool in the Galaxy Toolshed repository</label>: https://toolshed.g2.bx.psu.edu/repos/sblanck/smagexp

**Comment by Slugger70** [comment]
The tools will not install on either staging nor production.

**Comment by Slugger70** [comment]
This set of tools will require some work for them to be able to come up to scratch. I will close this issue for now.
